# Generated by Django 3.1.2 on 2020-10-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpage',
            name='keywords',
        ),
    ]
